# Generated by Django 3.1.3 on 2020-11-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_n', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_at', models.DateField()),
                ('lang', models.CharField(max_length=2)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buttons')),
            ],
        ),
    ]
